package io.rippledown.constants.chat

const val CONFIRM = "confirm"
const val REASON = "reason"
const val MORE_REASONS = "more reasons"
const val FIRST_REASON = "first reason"
const val ALLOW_REPORT_CHANGE = "allow report change"
const val IS_NOT_TRUE = "is not true"
const val ADD = "add"
const val REMOVE = "remove"
const val REPLACE = "replace"
const val STOP = "stop"
const val NO_COMMENTS = "No comments"
const val EXISTING_COMMENTS = "Existing comments"
const val WOULD_YOU_LIKE = "Would you like"
const val ADD_A_COMMENT = "add a comment"
const val REMOVE_A_COMMENT = "remove a comment"
const val REPLACE_A_COMMENT = "replace a comment"
const val WHAT_COMMENT = "What comment"
const val CHAT_BOT_NO_RESPONSE_MESSAGE = "Sorry, I don't understand. Please try again."
const val CHAT_BOT_PLACEHOLDER = "Your response..."
const val CHAT_BOT_DONE_MESSAGE = "Done"
const val START_ACTION = "start"

const val ADD_COMMENT = "AddComment"
const val REMOVE_COMMENT = "RemoveComment"
const val REPLACE_COMMENT = "ReplaceComment"
const val DEBUG_ACTION = "DEBUG_ACTION"
const val USER_ACTION = "UserAction"
const val UNDO_LAST_RULE = "UndoLastRule"
const val REVIEW_CORNERSTONES_ADD_COMMENT = "ReviewCornerstonesAddComment"
const val REVIEW_CORNERSTONES_REMOVE_COMMENT = "ReviewCornerstonesRemoveComment"
const val REVIEW_CORNERSTONES_REPLACE_COMMENT = "ReviewCornerstonesReplaceComment"

const val MOVE_ATTRIBUTE = "MoveAttribute"


