package io.rippledown.constants.chat

const val PLEASE_CONFIRM = "Please confirm"
const val ANY_CONDITIONS = "any conditions"
const val ANY_MORE_CONDITIONS = "any more conditions"
const val FIRST_CONDITION = "first condition"
const val IS_NOT_TRUE = "is not true"
const val COMMENT = "comment"
const val ADD = "add"
const val REMOVE = "remove"
const val REPLACE = "replace"
const val STOP = "stop"
const val NO_COMMENTS = "No comments"
const val EXISTING_COMMENTS = "Existing comments"
const val WOULD_YOU_LIKE = "Would you like"
const val ADD_A_COMMENT = "add a comment"
const val REMOVE_A_COMMENT = "remove a comment"
const val REPLACE_A_COMMENT = "replace a comment"
const val WHAT_COMMENT = "What comment"
const val CHAT_BOT_NO_RESPONSE_MESSAGE = "Sorry, I don't understand. Please try again."
const val CHAT_BOT_PLACEHOLDER = "Your response..."
const val CHAT_BOT_DONE_MESSAGE = "Done"
const val START_ACTION = "start"

const val ADD_ACTION = "ADD_ACTION"
const val REMOVE_ACTION = "REMOVE_ACTION"
const val REPLACE_ACTION = "REPLACE_ACTION"
const val STOP_ACTION = "STOP_ACTION"
const val DEBUG_ACTION = "DEBUG_ACTION"
const val USER_ACTION = "USER_ACTION"
