package io.rippledown.constants.rule

const val RULE_MAKER = "RULE_MAKER"
const val SELECTED_CONDITION_PREFIX = "CONDITION_PREFIX_"
const val AVAILABLE_CONDITION_PREFIX = "AVAILABLE_CONDITION_PREFIX_"
const val AVAILABLE_CONDITIONS = "AVAILABLE_CONDITIONS"
const val SELECTED_CONDITIONS = "SELECTED_CONDITIONS"
const val CURRENT_CONDITION = "CURRENT_CONDITION"
const val REMOVE_CONDITION_ICON_PREFIX = "MINUS_"
const val FINISH_RULE_BUTTON = "FINISH_RULE_BUTTON"
const val CANCEL_RULE_BUTTON = "CANCEL_RULE_BUTTON"
const val ADD_CONDITION_DESCRIPTION = "ADD_CONDITION_DESCRIPTION"
const val ADD_CONDITION_TEXT = "Add this condition to the rule"
