package io.rippledown.constants.interpretation


const val INTERPRETATION_TAB_ORIGINAL_LABEL = "Report"
const val INTERPRETATION_TAB_CONCLUSIONS_LABEL = "Comments"
const val INTERPRETATION_TAB_CHANGES_LABEL = "Differences"
const val INTERPRETATION_TAB_PREFIX = "interpretation_tab_"

const val INTERPRETATION_TABS = "interpretation_tabs"
const val INTERPRETATION_TAB_ORIGINAL = "$INTERPRETATION_TAB_PREFIX$INTERPRETATION_TAB_ORIGINAL_LABEL"
const val INTERPRETATION_TAB_CONCLUSIONS = "$INTERPRETATION_TAB_PREFIX$INTERPRETATION_TAB_CONCLUSIONS_LABEL"
const val INTERPRETATION_TAB_CHANGES = "$INTERPRETATION_TAB_PREFIX$INTERPRETATION_TAB_CHANGES_LABEL"
const val INTERPRETATION_PANEL_CONCLUSIONS = "interpretation_panel_$INTERPRETATION_TAB_CONCLUSIONS_LABEL"
const val INTERPRETATION_PANEL_CHANGES = "interpretation_panel_changes"
const val NO_CONCLUSIONS = "NO_CONCLUSIONS"

const val INTERPRETATION_TEXT_FIELD = "interpretation_text_area"
const val INTERPRETATION_VIEW_LABEL = "Report for this case"
const val DEBOUNCE_WAIT_PERIOD_MILLIS = 1_000L

const val CHANGE_INTERPRETATION_BUTTON = "CHANGE_INTERPRETATION_BUTTON"
const val CHANGE_INTERPRETATION_DROPDOWN = "CHANGE_INTERPRETATION_DROPDOWN"
const val CHANGE_INTERPRETATION = "Change interpretation"

const val ADD_COMMENT_MENU = "ADD_COMMENT_MENU"
const val REPLACE_COMMENT_MENU = "REPLACE_COMMENT_MENU"
const val REMOVE_COMMENT_MENU = "REMOVE_COMMENT_MENU"

const val ADD_COMMENT = "Add a comment"
const val NEW_COMMENT = "New comment"
const val COMMENT_TO_BE_REPLACED = "Comment to be replaced"
const val COMMENT_TO_BE_THE_REPLACEMENT = "Comment to be the replacement"
const val COMMENT_TO_BE_REMOVED = "Comment to be removed"
const val NO_COMMENTS = "There are no comments given for this case"

const val REPLACE_COMMENT = "Replace a comment"
const val REMOVE_COMMENT = "Remove a comment"
const val NEW_COMMENT_TEXT_FIELD = "ADD_COMMENT_TEXT_FIELD"
const val REPLACED_COMMENT_TEXT_FIELD = "REPLACED_COMMENT_TEXT_FIELD"
const val REPLACEMENT_COMMENT_TEXT_FIELD = "REPLACEMENT_COMMENT_TEXT_FIELD"
const val REMOVE_COMMENT_TEXT_FIELD = "REMOVE_COMMENT_TEXT_FIELD"

const val OK = "OK"
const val CANCEL_BUTTON_FOR_ADD_COMMENT = "CANCEL_BUTTON_FOR_ADD_COMMENT"
const val CANCEL_BUTTON_FOR_REPLACE_COMMENT = "CANCEL_BUTTON_FOR_REPLACE_COMMENT"
const val CANCEL_BUTTON_FOR_REMOVE_COMMENT = "CANCEL_BUTTON_FOR_REMOVE_COMMENT"

const val OK_BUTTON_FOR_REMOVE_COMMENT = "OK_BUTTON_FOR_REMOVE_COMMENT"
const val OK_BUTTON_FOR_ADD_COMMENT = "OK_BUTTON_FOR_ADD_COMMENT"
const val OK_BUTTON_FOR_REPLACE_COMMENT = "OK_BUTTON_FOR_REPLACE_COMMENT"

const val REMOVE_COMMENT_SELECTOR_PREFIX = "REMOVE_COMMENT_SELECTOR_"
const val REPLACE_COMMENT_SELECTOR_PREFIX = "REPLACE_COMMENT_SELECTOR_"
const val DROP_DOWN_TEXT_FIELD = "DROP_DOWN_TEXT_FIELD"
const val COMMENT_SELECTOR_LABEL = "COMMENT_SELECTOR_LABEL"



