package io.rippledown.constants.caseview

const val NUMBER_OF_CASES_ID = "number_of_cases_id"
const val CASE_HEADING = "Case: "
const val CASES = "Cases:"
const val CASEVIEW_CASE_NAME_ID = "case_view_case_name"
const val CASEVIEW_CORNERSTONE_CASE_NAME_ID = "case_view_cornerstone_case_name"
const val CASE_SELECTOR_ID = "case_selector_id"
const val CASE_VIEW_TABLE = "Case view table"
const val CASELIST_ID = "case_list_id"
const val CASE_NAME_PREFIX = "case_list_item_"
const val CASE_TABLE_ROW_PREFIX = "case_table_row_"
const val DATE_CELL_DESCRIPTION_PREFIX = "Date for episode"
const val REFERENCE_RANGE_CELL_DESCRIPTION_PREFIX = "Reference range for row"
const val REFERENCE_RANGE_HEADER_CELL_DESCRIPTION = "Reference ranges column"
const val ATTRIBUTE_CELL_DESCRIPTION_PREFIX = "Header for case data row"
const val ATTRIBUTE_HEADER_CELL_DESCRIPTION = "Attributes column"
const val ATTRIBUTE_HEADER_CELL_TEXT = "Attributes"
const val VALUE_CELL_DESCRIPTION_TEMPLATE = " value "