package io.rippledown.constants.api

const val CASE_NAME = "casename"
const val WAITING_CASES = "/api/waitingCasesInfo"
const val CONDITION_HINTS = "/api/conditionHints"
const val CASE = "/api/case"
const val PROCESS_CASE = "/api/processCase"
const val DELETE_PROCESSED_CASE_WITH_NAME = "/api/deleteProcessedCaseWithName"
const val MOVE_ATTRIBUTE_JUST_BELOW_OTHER = "/api/moveAttributeJustBelowOther"
const val VERIFIED_INTERPRETATION_SAVED = "/api/verifiedInterpretationSaved"
const val BUILD_RULE = "/api/buildRule"
const val KB_INFO = "/api/kbInfo"
const val CREATE_KB = "/api/createKB"
const val IMPORT_KB = "/api/importKB"
const val EXPORT_KB = "/api/exportKB"