package io.rippledown.constants.api

const val CASE_NAME = "casename"
const val WAITING_CASES = "/api/waitingCasesInfo"
const val CONDITION_HINTS = "/api/conditionHints"
const val CASE = "/api/case"
const val PROCESS_CASE = "/api/processCase"
const val DELETE_PROCESSED_CASE_WITH_NAME = "/api/deleteProcessedCaseWithName"
const val MOVE_ATTRIBUTE_JUST_BELOW_OTHER = "/api/moveAttributeJustBelowOther"
const val GET_OR_CREATE_ATTRIBUTE = "/api/attribute/getOrCreate"
const val GET_OR_CREATE_CONCLUSION = "/api/conclusion/getOrCreate"
const val GET_OR_CREATE_CONDITION = "/api/condition/getOrCreate"
const val START_SESSION_TO_ADD_CONCLUSION = "/api/startSessionToAddConclusion"
const val START_SESSION_TO_REPLACE_CONCLUSION = "/api/startSessionToReplaceConclusion"
const val ADD_CONDITION = "/api/addCondition"
const val COMMIT_SESSION = "/api/commitSession"
const val VERIFIED_INTERPRETATION_SAVED = "/api/verifiedInterpretationSaved"
const val BUILD_RULE = "/api/buildRule"
const val START_RULE_SESSION = "/api/startRuleSession"
const val SELECT_CORNERSTONE = "/api/selectCornerstone"
const val UPDATE_CORNERSTONES = "/api/updateCornerstones"
const val INDEX_PARAMETER = "index"
const val KB_INFO = "/api/kbInfo"
const val DELETE_KB = "/api/deleteKB"
const val KB_LIST = "/api/kbList"
const val CREATE_KB = "/api/createKB"
const val IMPORT_KB = "/api/importKB"
const val EXPORT_KB = "/api/exportKB"